---
# wywolanie: $ ansible-playbook -i hosts site.yml -kK
# ansible-playbook -i /home/kmonticolo/ansible/playbooks/vpostest/hosts /home/kmonticolo/ansible/playbo


- hosts: polecommapptest
  sudo: yes
  user: kmonticolo_adm

#- hosts: polecommapptestskany
  #sudo: yes
  #user: kmonticolo_adm

  #vars:
  #  - db_name: drupal
  #  - db_user: drupal_user
  #  - db_password: drupal_db_pass
    
  roles:
    - jboss
    #- update
    #- php
    #- mysql
    #- drupal
